# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASPO_new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASPO_new.Question')),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='consentAcceptText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='consentQuestionText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='consentRefuseText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='consentShowOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
