# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASPO_new', '0002_auto_20170526_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
