# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('idAnswer', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('answerColor', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disable',
            fields=[
                ('idDisable', models.IntegerField(primary_key=True, serialize=False)),
                ('idOfQuestionToDisable', models.IntegerField(blank=True, null=True)),
                ('idAnswer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ASPO_new.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idQuestion', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('questionType', models.TextField(blank=True, null=True)),
                ('idGroup', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAnswer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ASPO_new.Answer')),
                ('idQuestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ASPO_new.Question')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ASPO_new.User')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='idQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ASPO_new.Question'),
        ),
    ]
