# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencies',
            fields=[
                ('answer_id', models.IntegerField(primary_key=True)),
                ('prev_question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_id', models.IntegerField(primary_key=True)),
            ],
            options={
                'managed': False,
                'db_table': 'dependencies',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswers',
            fields=[
                ('answer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('flag', models.IntegerField(blank=True, null=True)),
                ('order_nr', models.IntegerField(blank=True, null=True)),
                ('question_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'question_answers',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('order_nr', models.IntegerField(blank=True, null=True, unique=True)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('user_id', models.CharField(max_length=23, primary_key=True, serialize=False)),
                ('question_id', models.IntegerField(blank=True, null=True)),
                ('answer_id', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'user_answers',
            },
        ),
    ]
