# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASPO_new', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dependencies',
            table='Dependencies',
        ),
        migrations.AlterModelTable(
            name='questionanswers',
            table='QuestionAnswers',
        ),
        migrations.AlterModelTable(
            name='questions',
            table='Questions',
        ),
        migrations.AlterModelTable(
            name='useranswers',
            table='UserAnswers',
        ),
    ]
